#ifndef GAME_CONSTANTS_H
#define GAME_CONSTANTS_H

#define BASE_SCREEN_WIDTH 1280
#define BASE_SCREEN_HEIGHT 720
#define GROUND_LEVEL GLOBAL_GROUND_LEVEL
#define WORLD_SCALE GLOBAL_WORLD_SCALE

extern float GLOBAL_GROUND_LEVEL;
extern float GLOBAL_WORLD_SCALE;

#endif